### ISSUE TITLE
Déplacement du repo dans l'organisation https://github.com/konnectors

### ISSUE THREAD

**Issue by doubleface** [konnectors/cozy-konnector-v3-ameli#17]
@briced Tu es intéressé pour faire le déplacement du connecteur ameli vers l'organisation https://github.com/konnectors ?

Tu garderais bien sûr tous tes droits sur le repo mais on pourrait plus facilement intégrer ce connecteur dans notre systeme de deploiement, mise à jour automatique. Et on pourrait plus facilement donner des droits sur le repo à toute l'équipe cozy.

**Comment by briced** [comment]
Que des avantages! Comment je fais ça?

**Comment by briced** [comment]
Done

**Comment by doubleface** [comment]
Désolé, pas pu te répondre à temps
